FROM ghcr.io/dhhyi/dcc-base-node

RUN npm --global install @cicada-lang/cicada

USER vscode

LABEL "org.opencontainers.image.description"="VSCode devcontainer for cicada" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
