FROM ghcr.io/dhhyi/dcc-base-ubuntu

USER ubuntu

SHELL ["/usr/bin/env", "fish", "-c"]
RUN mise use -g node@lts

LABEL "org.opencontainers.image.description"="VSCode devcontainer for node" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
