FROM ghcr.io/dhhyi/dcc-devcontainer-debian

USER root

RUN mise use -g deno

USER vscode

LABEL "org.opencontainers.image.description"="VSCode devcontainer for deno" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
