root: true
overrides:
  - files:
      - "*.js"
    extends: standard
    parserOptions:
      ecmaVersion: latest
      sourceType: module
    rules:
      quotes:
        - warn
        - single
        - avoidEscape: true
      semi:
        - warn
        - always
      comma-dangle:
        - off
      space-before-function-paren:
        - off
  - files:
      - "*.ts"
    plugins:
      - "@typescript-eslint"
      - import
    extends:
      - eslint:recommended
      - plugin:@typescript-eslint/recommended
      - plugin:import/errors
      - plugin:import/warnings
      - plugin:import/typescript
    parser: "@typescript-eslint/parser"
    rules:
      quotes:
        - warn
        - single
        - avoidEscape: true
      import/no-unresolved: [off]
      import/named: [off]
      import/namespace: [error]
      import/no-named-as-default: [error]
      import/export: [error]
      import/order:
        - error
        - groups: ["builtin", "external", "parent", "sibling", "index"]
          newlines-between: always
          alphabetize:
            order: asc
            caseInsensitive: false
