plugins:
  - prettier-plugin-sh
singleQuote: true
trailingComma: es5
overrides:
  - options:
      parser: json
    files:
      - "*.json"
  - options:
      parser: yaml
      singleQuote: false
    files:
      - "*.yaml"
      - "*.yml"
  - options:
      parser: sh
      indent: 4
    files:
      - "*.sh"
      - .git*
      - .prettierignore
      - Dockerfile
