[tools]
node = "24"
pnpm = "latest"

[hooks]
postinstall = '''
pnpm setup
if command -v devcontainer >/dev/null 2>&1; then
	echo "devcontainer CLI already installed"
else
	pnpm add -g npm:@devcontainers/cli
fi
'''

[settings]
experimental = true

[settings.npm]
package_manager = "pnpm"

[env]
_.path = { path = ["{{env.HOME}}/.local/share/pnpm/bin"] }
