FROM ghcr.io/dhhyi/dcc-devcontainer-debian

USER vscode

SHELL ["/usr/bin/env", "fish", "-c"]
RUN mise use -g java@21

LABEL "org.opencontainers.image.description"="VSCode devcontainer for java" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
