FROM ghcr.io/dhhyi/dcc-base-ubuntu

ENV PATH="$HOME/.local/share/mise/shims:$PATH"
SHELL ["/usr/bin/env", "fish", "-c"]

USER ubuntu

LABEL "org.opencontainers.image.description"="VSCode devcontainer for ubuntu" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
