FROM ghcr.io/dhhyi/dcc-devcontainer-java

USER vscode

RUN mise use -g groovy

LABEL "org.opencontainers.image.description"="VSCode devcontainer for groovy" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
