FROM ghcr.io/dhhyi/dcc-base-node

RUN npm i -g ts-node

USER vscode

LABEL "org.opencontainers.image.description"="VSCode devcontainer for typescript" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
