FROM ghcr.io/dhhyi/dcc-base-debian

SHELL ["/usr/bin/env", "fish", "-c"]

USER vscode

LABEL "org.opencontainers.image.description"="VSCode devcontainer for debian" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
