FROM ghcr.io/dhhyi/dcc-base-debian

ENV PATH="$HOME/.local/share/mise/shims:$PATH"
SHELL ["/usr/bin/env", "fish", "-c"]

USER vscode

LABEL "org.opencontainers.image.description"="VSCode devcontainer for debian" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
