FROM ghcr.io/dhhyi/dcc-devcontainer-node

LABEL "org.opencontainers.image.description"="VSCode devcontainer for javascript" "org.opencontainers.image.source"="https://github.com/dhhyi/devcontainer-creator"
