name: baseTemplate

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      skip:
        required: false
        type: boolean

jobs:
  build:
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base-${{ inputs.name }}
        run: npm run build-base ${{ inputs.name }}

      - name: Publish base-${{ inputs.name }}
        run: docker push ghcr.io/dhhyi/dcc-base-${{ inputs.name }}
