name: dccTemplate

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      skip:
        required: false
        type: boolean

jobs:
  build:
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: |
          curl -so- https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/bundle.js | node - \
            examples/${{ inputs.name }}.yaml \
            --test \
            --debug \
        name: dcc

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker push ghcr.io/dhhyi/dcc-devcontainer-${{ inputs.name }}:latest
        name: publish
