name: dccTemplate

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      skip:
        required: false
        type: boolean

jobs:
  build:
    if: ${{ !inputs.skip }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install patched devcontainer CLI
        run: npm install -g github:dhhyi/devcontainers-cli\#fix/propagate-cache-from-dist

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: >
          curl -so- https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/bundle.js | node -
          https://raw.githubusercontent.com/dhhyi/devcontainer-creator/main/examples/${{ inputs.name }}.yaml
          dist/test/${{ inputs.name }}
          --test
          --debug
          --dump-meta
          --name "Example devcontainer for ${{ inputs.name }}"
          --push
        name: dcc

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.name }}
          path: dist/test/${{ inputs.name }}
