name: Update dist Branch
on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/dist.yml
      - templates/**
      - create.mjs
      - package.json
      - package-lock.json
      - webpack.config.js

jobs:
  deploy:
    name: Update dist Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
