name: Update example-app Branch
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Update dist Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          CLEAN: true # Automatically remove deleted files from the deploy branch
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
