name: examples

on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip }}
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@v3
        with:
          path: output

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: devcontainers
          FOLDER: output
          SQUASH_HISTORY: false
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
