name: examples

on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip }}
    steps:
      - uses: actions/checkout@master

      - name: Download Script
        run: |
          mkdir -p dist
          curl -sL https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/bundle.js > dist/bundle.js

      - name: Build Examples
        run: npm run build-examples

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: devcontainers
          FOLDER: dist/test
          SQUASH_HISTORY: false
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
