name: examples

on:
  workflow_call:
    inputs:
      skip:
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !inputs.skip }}
    steps:
      - uses: actions/checkout@master

      - run: |
          for yaml in examples/*.yaml
          do
            lang=$(basename $yaml .yaml)
            curl -so- https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/bundle.js | node - \
              https://raw.githubusercontent.com/dhhyi/devcontainer-creator/main/examples/$lang.yaml \
              dist/test/$lang \
              --dump-meta \
              --name "Example devcontainer for $lang" \
              --cache-from ghcr.io/dhhyi/dcc-devcontainer-$lang:latest
          done

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: devcontainers
          FOLDER: dist/test
          SQUASH_HISTORY: false
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
