name: Publish
on:
  push:
    branches:
      - main

jobs:
  deployBundle:
    name: Update dist Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: |
          npm exec pnpm -- i --prod --ignore-scripts
          npm exec pnpm run build

      - name: Test
        run: ./run-tests.sh

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  checkLangCI:
    name: Check CI Languages
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.check-lang-ci.outputs.languages }}
      buildLanguages: ${{ steps.check-lang-ci.outputs.buildLanguages }}
      buildBase: ${{ steps.check-lang-ci.outputs.buildBase }}
      baseImages: ${{ steps.check-lang-ci.outputs.baseImages }}
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Check
        id: check-lang-ci
        run: |
          npm exec pnpm -- i --prod --ignore-scripts
          git diff --name-only HEAD~ | node check-lang-ci.js >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  deployFeatures:
    needs: [checkLangCI]
    if: needs.checkLangCI.outputs.buildBase == 'true'
    name: Deploy Features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Test Features
        run: devcontainer features test features

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./features"
          disable_matcher: true
          check_together: "yes"

      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          publish-features: true
          base-path-to-features: ./features/src
          generate-docs: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  baseImage:
    needs: [deployFeatures, checkLangCI]
    if: needs.checkLangCI.outputs.buildBase == 'true'
    name: Update Base Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull cache
        continue-on-error: true
        run: docker pull ghcr.io/dhhyi/dcc-base-debian

      - name: Build base-debian
        run: devcontainer build --workspace-folder base-images/debian --cache-from ghcr.io/dhhyi/dcc-base-debian --image-name ghcr.io/dhhyi/dcc-base-debian

      - name: Publish base-debian
        run: docker push ghcr.io/dhhyi/dcc-base-debian

  dependentBaseImages:
    needs: [checkLangCI, baseImage]
    if: needs.checkLangCI.outputs.buildBase == 'true'
    name: Update Dependent Base Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: ${{ fromJson(needs.checkLangCI.outputs.baseImages) }}
    steps:
      - uses: actions/checkout@master

      - name: Install latest devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull cache
        continue-on-error: true
        run: docker pull ghcr.io/dhhyi/dcc-base-${{ matrix.lang }}

      - name: Build base-${{ matrix.lang }}
        run: devcontainer build --workspace-folder base-images/${{ matrix.lang }} --cache-from ghcr.io/dhhyi/dcc-base-${{ matrix.lang }} --image-name ghcr.io/dhhyi/dcc-base-${{ matrix.lang }}

      - name: Publish base-${{ matrix.lang }}
        run: docker push ghcr.io/dhhyi/dcc-base-${{ matrix.lang }}

  test:
    needs: [deployBundle, checkLangCI, baseImage, dependentBaseImages]
    if: ${{ needs.checkLangCI.outputs.buildLanguages == 'true' && always() }}
    name: Test and Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lang: ${{ fromJson(needs.checkLangCI.outputs.languages) }}
    steps:
      - uses: actions/checkout@master

      - run: |
          curl -so- https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/bundle.js | node - \
            examples/${{ matrix.lang }}.yaml \
            --test \
            --debug \
            --cache-from ghcr.io/dhhyi/dcc-devcontainer-${{ matrix.lang }}:latest \
            --tag devcontainer-${{ matrix.lang }}
        name: dcc

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "FROM devcontainer-${{ matrix.lang }}" | docker build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --label org.opencontainers.image.source="https://github.com/dhhyi/devcontainer-creator" \
            --label org.opencontainers.image.description="VSCode devcontainer for ${{ matrix.lang }}" \
            -t ghcr.io/dhhyi/dcc-devcontainer-${{ matrix.lang }}:latest \
            -
          docker push ghcr.io/dhhyi/dcc-devcontainer-${{ matrix.lang }}:latest
        name: publish

  publishExamples:
    needs: [test]
    if: ${{ needs.checkLangCI.outputs.buildLanguages == 'true' && always() }}
    name: Publish Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: |
          for yaml in examples/*.yaml
          do
            lang=$(basename $yaml .yaml)
            curl -so- https://raw.githubusercontent.com/dhhyi/devcontainer-creator/dist/bundle.js | node - \
              https://raw.githubusercontent.com/dhhyi/devcontainer-creator/main/examples/$lang.yaml \
              dist/test/$lang \
              --dump-meta \
              --name "Example devcontainer for $lang" \
              --cache-from ghcr.io/dhhyi/dcc-devcontainer-$lang:latest
          done

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: devcontainers
          FOLDER: dist/test
          SQUASH_HISTORY: false
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
