name: Check Languages
on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/test.yml
      - templates/**
      - examples/**
      - create.mjs
      - package.json
      - package-lock.json
      - webpack.config.js
      - test.sh

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: bash test.sh

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: devcontainers
          FOLDER: dist/test
          SQUASH_HISTORY: false
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
