name: Check Languages
on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/test.yml
      - templates/**
      - examples/**
      - create.mjs
      - package.json
      - webpack.config.js
      - test.sh
      - publish.sh

jobs:
  test:
    name: Test and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: bash test.sh

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: bash publish.sh

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: devcontainers
          FOLDER: dist/test
          SQUASH_HISTORY: false
          SKIP_EMPTY_COMMITS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
